import { TodoElement } from "../model/interfaces";

const mockData: TodoElement[] = [
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
  {
    id: "someid",
    homeId: null,
    name: "somename",
    description: "somedescription",
    createdOn: "somedate",
    createdBy: "someone",
    deadLine: null,
    completedOn: "somedate",
    completedBy: "someone",
  },
];

export const Todo = () => {
  return (
    <div className="fillscreen overflow-auto">
      <div className="text-2xl text-center">Huskeliste</div>
      <table className="w-screen">
        <thead className="bg-slate-500 sticky">
          <tr>
            <th>Navn</th>
            <th>Ferdig</th>
          </tr>
        </thead>
        <tbody>
          {mockData.map((element, index) => (
            <tr key={index} className="font-semibold">
              <td className="text-left px-3">{element.name}</td>
              <td className="text-center">{element.completedOn}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
